### ISSUE TITLE
Please host your demo somewhere else

### ISSUE THREAD

**Issue by JeyKeu** [oskarkrawczyk/tour.js#3]
Github doesn't want people to link resources (js,images, css) right from your Github Repo

**Comment by curlup** [comment]
+1

Demo isn't working due to js error
`Refused to execute script from 'https://raw.github.com/oskarkrawczyk/tour.js/master/demo/mootools.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled`

**Comment by oskarkrawczyk** [comment]
I'm not maintaining this project anymore. Just put the code in JSFiddle and pick MooTools as the framework.
